// Platform-agnostic resolver for the heavy binary assets (audio mp3s,
// illustrations, download bundles). These no longer live in git / on Vercel —
// they're served from a public Supabase Storage bucket + CDN. Both web and
// mobile build the same URLs through here so there's a single source of truth.
//
// Small metadata (audio manifest.json, the text .mdx + zip) stays in the repo;
// only the large media is offsite. See scripts/upload-assets-to-supabase.ts.

import versionMap from "./asset-version.json";

/**
 * One entry per uploaded file: a short content hash for cache-busting and the
 * byte size (so size labels can render without a local copy). Generated by the
 * upload script; an empty map (nothing uploaded yet) just means unversioned
 * URLs and hidden sizes — never an error.
 */
export type AssetVersionEntry = {
  v: string;
  bytes: number;
  // ASCII bucket key, present only when the original path isn't ASCII-safe
  // (e.g. Chinese narration filenames — Supabase rejects non-ASCII keys). When
  // set, the CDN URL uses this instead of the raw path. See the upload script.
  key?: string;
};
const VERSION_MAP = versionMap as Record<string, AssetVersionEntry>;

// Public CDN base for the Supabase `assets` bucket. Not a secret (the same
// project URL ships as NEXT_PUBLIC_/EXPO_PUBLIC_SUPABASE_URL already), so it's
// safe to hardcode as the default; an env override lets us repoint without a
// code change. Web inlines NEXT_PUBLIC_*, mobile inlines EXPO_PUBLIC_*.
const DEFAULT_ASSET_BASE =
  "https://ffoiltrarbdbibmymlqm.supabase.co/storage/v1/object/public/assets";

function envBase(): string | undefined {
  // Guarded so a missing `process` (some RN contexts) can't throw.
  if (typeof process === "undefined" || !process.env) return undefined;
  return (
    process.env.NEXT_PUBLIC_ASSET_BASE ?? process.env.EXPO_PUBLIC_ASSET_BASE
  );
}

export const ASSET_BASE = (envBase() ?? DEFAULT_ASSET_BASE).replace(/\/$/, "");

/** Normalize a caller-supplied path to a clean bucket-relative key. */
function normalize(relPath: string): string {
  return relPath.replace(/^\/+/, "");
}

/** True once the file has been uploaded (i.e. it's in the version map). */
export function hasAsset(relPath: string): boolean {
  return normalize(relPath) in VERSION_MAP;
}

/** Byte size of an uploaded asset, or null if not uploaded yet. */
export function assetSize(relPath: string): number | null {
  return VERSION_MAP[normalize(relPath)]?.bytes ?? null;
}

/**
 * Absolute CDN URL for a bucket-relative path (e.g. "audio/en/first-talk/01.mp3"),
 * cache-busted with `?v=<hash>` when the file is in the version map.
 */
export function assetUrl(relPath: string): string {
  const path = normalize(relPath);
  const entry = VERSION_MAP[path];
  // Prefer the ASCII bucket key when one was recorded (non-ASCII originals).
  const url = `${ASSET_BASE}/${entry?.key ?? path}`;
  return entry ? `${url}?v=${entry.v}` : url;
}

/**
 * Like assetUrl, but forces a save-as instead of opening inline. The HTML
 * `download` attribute is ignored cross-origin (the CDN is a different origin),
 * so we use Supabase Storage's `download` flag, which sets
 * `Content-Disposition: attachment`. Use for book/zip downloads; use plain
 * assetUrl for media played/shown in-page (audio, img).
 */
export function assetDownloadUrl(relPath: string): string {
  const url = assetUrl(relPath);
  return url.includes("?") ? `${url}&download` : `${url}?download`;
}
