/**
 * Write dist/MANIFEST.md — a human-readable index of the built book artifacts:
 * when it was generated, every deliverable (size + last-modified), and a recent
 * changelog pulled from git history.
 *
 * Regenerated as the final step of the build pipeline (see `pnpm build-all`) so
 * it always reflects the current contents of dist/ + public/downloads/.
 *
 * Run: pnpm build-manifest
 */

import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const DIST = join(ROOT, "dist");
const OUT = join(DIST, "MANIFEST.md");

// Deliverable groups: a label + a directory scanned NON-recursively (the nested
// per-variant folders under dist/print and dist/kdp are build scratch).
const GROUPS: { label: string; dir: string }[] = [
  { label: "Reader downloads (served by the site)", dir: "public/downloads" },
  { label: "Screen PDF", dir: "dist/pdf" },
  { label: "EPUB & cover art", dir: "dist/ebook" },
  { label: "Print PDFs (self-contained proofs)", dir: "dist/print" },
  { label: "KDP paperback package", dir: "dist/kdp" },
  { label: "Storyboard", dir: "dist/storyboard" },
  { label: "Audiobook", dir: "dist/audiobook" },
];

const DELIVERABLE_EXT = new Set([".pdf", ".epub", ".jpg", ".jpeg", ".png", ".m4b", ".mp3"]);

function ext(name: string): string {
  const i = name.lastIndexOf(".");
  return i < 0 ? "" : name.slice(i).toLowerCase();
}

function humanSize(bytes: number): string {
  if (bytes >= 1024 * 1024) return `${(bytes / (1024 * 1024)).toFixed(2)} MB`;
  return `${Math.max(1, Math.round(bytes / 1024))} KB`;
}

function stamp(d: Date): string {
  // UTC, unambiguous: "2026-05-30 14:32 UTC".
  return `${d.toISOString().slice(0, 16).replace("T", " ")} UTC`;
}

type Row = { rel: string; size: string; modified: string };

function scanGroup(dir: string): Row[] {
  const abs = join(ROOT, dir);
  if (!existsSync(abs)) return [];
  return readdirSync(abs, { withFileTypes: true })
    .filter((e) => e.isFile() && DELIVERABLE_EXT.has(ext(e.name)))
    .map((e) => {
      const full = join(abs, e.name);
      const st = statSync(full);
      return {
        rel: relative(ROOT, full),
        size: humanSize(st.size),
        modified: stamp(st.mtime),
      };
    })
    .sort((a, b) => a.rel.localeCompare(b.rel));
}

type Commit = { date: string; hash: string; subject: string };

// Recent commits, optionally limited to a pathspec (e.g. "packages/content").
function gitLog(limit: number, pathspec?: string): Commit[] {
  try {
    // %x09 = tab field separator (commit subjects never contain tabs).
    const args = ["log", `-n${limit}`, "--date=short", "--pretty=format:%ad%x09%h%x09%s"];
    if (pathspec) args.push("--", pathspec);
    const out = execFileSync("git", args, { cwd: ROOT, encoding: "utf8" });
    return out
      .split("\n")
      .filter(Boolean)
      .map((line) => {
        const [date, hash, subject] = line.split("\t");
        return { date, hash, subject };
      });
  } catch {
    return [];
  }
}

function fmtCommit(c: Commit): string {
  return `- \`${c.date}\` ${c.subject} (\`${c.hash}\`)`;
}

function main(): void {
  if (!existsSync(DIST)) mkdirSync(DIST, { recursive: true });

  const now = new Date();
  const lines: string[] = [];
  lines.push("# Plain Dharma — Build Manifest");
  lines.push("");
  lines.push(`_Last updated: **${stamp(now)}**_`);
  lines.push("");
  lines.push(
    "Index of the generated book artifacts. Regenerated by `pnpm build-manifest` " +
      "(the final step of `pnpm build-all`)."
  );
  lines.push("");

  // Content source freshness, up top — the MDX/registry in packages/content is
  // the source of truth every artifact below is built from.
  const contentCommits = gitLog(8, "packages/content");
  lines.push("## Content source — recent changes (`packages/content`)");
  lines.push("");
  if (contentCommits.length > 0) {
    lines.push(`_Last content change: **${contentCommits[0].date}**_`);
    lines.push("");
    lines.push(...contentCommits.map(fmtCommit));
  } else {
    lines.push("_No content history available._");
  }
  lines.push("");

  let totalFiles = 0;
  for (const group of GROUPS) {
    const rows = scanGroup(group.dir);
    if (rows.length === 0) continue;
    totalFiles += rows.length;
    lines.push(`## ${group.label}`);
    lines.push("");
    lines.push("| File | Size | Last built |");
    lines.push("|---|---|---|");
    for (const r of rows) lines.push(`| \`${r.rel}\` | ${r.size} | ${r.modified} |`);
    lines.push("");
  }

  lines.push(`_${totalFiles} artifact${totalFiles === 1 ? "" : "s"} tracked._`);
  lines.push("");
  lines.push("## Changelog (recent commits)");
  lines.push("");
  const recent = gitLog(15);
  lines.push(...(recent.length > 0 ? recent.map(fmtCommit) : ["- (git history unavailable)"]));
  lines.push("");

  writeFileSync(OUT, lines.join("\n"));
  console.log(`[build-manifest] wrote ${relative(ROOT, OUT)} (${totalFiles} artifacts)`);
}

main();
